# Generated by Django 4.0.10 on 2023-05-09 04:45

import avatar.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatarImage',
            field=avatar.models.AvatarField(),
        ),
    ]
